### ISSUE TITLE
Paracon freeze after configuration screen with QTsoundmodem

### ISSUE THREAD

**Issue by ClaudeMa** [mfncooper/paracon#12]
Unable to start Paracon on Debian 12
Qtsoundmodem on local machine 
Paracon start and display configuration sceen
after filling all setup field ans doing "okay" Paracon freeze and nothing happen
I need to kill it with CTRL+C
paracon.log is empty
tryed with localhost, 127.0.0.1 and ip of computer no change
![Capture d’écran_2024-10-05_11-58-32](https://github.com/user-attachments/assets/5089fb04-0c07-490e-8f55-977754ac09d3)

**Comment by mfncooper** [comment]
It turns out that there were a few issues with QtSoundModem's implementation of the AGWPE protocol. I've been working with John, G8BPQ, who ported and maintains QtSoundModem, and all of these issues are now resolved. John expects to release a new version of QtSoundModem soon. In the meantime, if you don't want to wait, and are willing to build it from source code, there is a test version available here:

https://www.cantab.net/users/john.wiseman/Downloads/Test/QtSM73Beta4Source.zip

I have tested this version, running on Linux Mint 21, and found no issues using it with Paracon.

**Comment by ClaudeMa** [comment]
Thanks Martin

I will try this new version of QTsm as soon as possible





Le mar. 15 oct. 2024 à 00:01, Martin Cooper ***@***.***> a
écrit :

**Comment by mfncooper** [comment]
The new official release of QtSoundModem is now available via its website:

https://www.cantab.net/users/john.wiseman/Documents/QtSoundModem.html

and in the Downloads section of that site:

https://www.cantab.net/users/john.wiseman/Downloads/

**Comment by ClaudeMa** [comment]
Thanks work now
